### ISSUE TITLE
RSS feed URL appears to return invalid page

### ISSUE THREAD

**Issue by ocdtrekkie** [justinribeiro/blog-pwa#27]
https://justinribeiro.com/data/chronicle/index.xml should return an RSS feed (I am looking to subscribe to your blog), however, it returns a blank page with your page header.

**Comment by justinribeiro** [comment]
Fixed via #31 by fixing both the SW and the page open. Cheers for the ticket!

**Comment by ocdtrekkie** [comment]
Thanks! Subscribed! :D
